---
title: "R Notebook"
output: html_notebook
---

```{r}
library(mlr3verse)
library(mlr3learners)
library(ggplot2)
library(Metrics)

data_train <- read.csv("train.csv")
data_test <- read.csv("test.csv")
```


```{r}
# as mlr3 task
task_train <- as_task_classif(data_train, target = "Response")
```

```{r}
# create a simple pipeline object to select features "Ins_Age", "Ht", "Wt", "BMI"
selected_features = c("Ins_Age", "Ht", "Wt", "BMI")

po_select = po("select", selector = function(task) selected_features)

# only chose a random half of the points in data_train in pipeline
po_sample = po("subsample", frac = 0.5, replace=FALSE)

# Create a pipeline with the selector
pipeline = po_sample %>>% po_select %>>% lrn("classif.ranger")

# Train the pipeline
learner = as_learner(pipeline)

# do cross validation
rr = resample(task_train, learner, rsmp("cv", folds = 3))
```


```{r}
# Load necessary libraries
library(mlr3)
library(R6)

# Define the custom measure class
MeasureClassifQuadraticWeightedKappa = R6::R6Class("MeasureRegrQuadraticWeightedKappa",
  inherit = mlr3::MeasureClassif, # regression measure
  public = list(
    initialize = function() { # initialize class
      super$initialize(
        id = "quadratic_weighted_kappa", # unique ID
        packages = "Metrics", # package dependency
        properties = character(), # no special properties
        predict_type = "response", # measures response prediction
        range = c(-1, 1), # results in values between (-1, 1)
        minimize = FALSE # larger values are better
      )
    }
  ),

  private = list(
    # define score as private method
    .score = function(prediction, ...) {
      truth_int = as.integer(as.factor(prediction$truth))
      response_int = as.integer(as.factor(prediction$response))
      # define loss
      quadratic_weighted_kappa = function(truth, response) {
        Metrics::ScoreQuadraticWeightedKappa(truth, response)
      }
      # call loss function
      quadratic_weighted_kappa(truth_int, response_int)
    }
  )
)


# Create a custom measure object
measure = MeasureClassifQuadraticWeightedKappa$new()

# Print the measure object
print(measure)
```

```{r}
# Create a custom measure object
measure = MeasureClassifQuadraticWeightedKappa$new()
rr$aggregate(measure)
```
```{r}
# Train the learner on the "full" data
learner$train(task_train)
```

```{r}
preds = learner$predict_newdata(newdata = data_test)
preds
```
```{r}
results = data.frame(Id = data_test$Id, Response = as.integer(preds$response))
head(results)
```
```{r}
# Save the results to a CSV file, do not put strings in "
write.csv(results, "my_submissions/submission.csv", row.names = FALSE)
```

